### ISSUE TITLE
P4G-Save-Tool on Linux

### ISSUE THREAD

**Issue by ghost** [fendevel/P4G-Save-Tool#11]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by OMGitsHYPER** [comment]
It did not work, so I set up a Virtual Machine.
