### ISSUE TITLE
Save editor does not account for Girlfriend Flag (Uses wrong S.Link IDs)

### ISSUE THREAD

**Issue by Kosyne** [fendevel/P4G-Save-Tool#2]
Possibly related to #1 
The page [here](https://amicitia.miraheze.org/wiki/Data00xx.bin) here lists a fair number of ?'s and duplicate ID's under the social link identifier section.

The duplicate IDs represent the 'girlfriend flag'.

`0B` is the ID the editor uses for Chie. However, that is the flag for when she is your girlfriend.
Taken from my normal game, `0C` is the default, non-girlfriend chie.

I imagine it is like this for all the other duplicate entries.

Unrelated, but not worth opening another issue about right now, there is an `04` on certain S.Links, such as jester, hierophant, and devil that isn't preserved when writing the save file (even if you didn't modify the social link section)
example line: `09 00 0A 00 00 00 00 00 00 00 00 00 04 00 00 00`
After it is saved: `09 00 0A 00 00 00 00 00 00 00 00 00 00 00 00 00`

**Comment by DuIslingr** [comment]
This is related to #1 If you are maxed and/or not on the lovers route and you edit the save even if not touching social links, the editor removes them. Had to do this several times. damn near broke the game for me as it caused my sun link to disappear and i hadnt realized and was not able to activate the march event with sun link. took some fiddling to get an event to work. So this should be somewhere at the top of the list to be fixed.

**Comment by Kosyne** [comment]
It may, as the ones that got nuked on me were all potential girlfriend (but werent in my save): Chie, Rise, and Ayane. Aside from Ayane, the others weren't at max level, so them being maxed isn't the problem.

And yeah, was a bit of a pain to fix. Eventually ended up copying out the S.Link section from an old save and modified it to the values I remembered them having.

**Comment by HeadPhones2016** [comment]
Would you mind detailing how exactly you managed to revert those values back? I realized these same errors during the bus scene when I couldn't reach Yukiko. Also noticed it changed my relationship statuses with some of them and my expression stat was decreased by one level for some reason when the save was at max before using the editor.

**Comment by Kosyne** [comment]
Get a hex editor. I used HxD. Open the bad save file in it, as well as an old good one.
Scroll down to about line 1970. Thats the social link section. Look on the link I posted in the first post for what those values mean. It'll give you a whole bunch of useful values. (However, the link uses all decimal values, and they should be hexadecimal values. So use an online converter or something to get an idea of the values you'll be needing. For instance, for rank 10, the 10 would be 0A in hexadecimal.)

I just copied that section out of an old good save, into the borked save. Note you need to overwrite the existing section (via the paste overwrite or similar option), otherwise you'll bork your save.

As for the expression thing, I haven't looked into that one, but if you look on that wiki page, you can probably figure it out.

**Comment by fendevel** [comment]
Thanks for the insight, @Kosyne! I'm working on it right now so expect an update within an hour or two.
