### ISSUE TITLE
Feature: Comboboxes should autocomplete while typing

### ISSUE THREAD

**Issue by yor-so** [fendevel/P4G-Save-Tool#4]
All comboboxes should autocomplete while typing.
For example: in the skill comboboxes, if I type "ag" it should select "agi", but if I type "agid" it should select "agidyne".
This will decrease the editing time drastically.

**Comment by fendevel** [comment]
I tried this on the initial build in various ways however it lagged hard because of the large number of skills to filter. Maybe down the road if skills get ordered like the items on the inventory tab I'll do it but for now this is shelved.

**Comment by yor-so** [comment]
I fork it and did it, please check the pull request. It doesn't lag for me..
Thanks!
